# Displays a "Sponsor" button on the repository.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [sotashimozono]
# Other platforms (uncomment / fill as needed):
# custom: ["https://…"]
# ko_fi: your_username
# buy_me_a_coffee: your_username
